chore: fail melos script if any of executed commands fails

diff --git a/melos.yaml b/melos.yaml
--- a/melos.yaml
+++ b/melos.yaml
@@ -147,6 +147,10 @@ scripts:
 
   format-apply:
     run: |
+      # The set -o pipefail option ensures that a pipeline returns the exit
+      # status of the first command that fails, instead of the last command.
+      set -o pipefail
+
       melos exec -c 1 --dir-exists="lib" -- "find . -name "*.dart" ! -name "*.g.dart" ! -path '*/generated/*' | tr '\n' ' ' | xargs dart format --fix" &&
       melos exec -c 1 --dir-exists="test" -- "find . -name "*.dart" ! -name "*.g.dart" ! -path '*/generated/*' | tr '\n' ' ' | xargs dart format --fix" &&
       melos exec -c 1 --dir-exists="integration_test" -- "find . -name "*.dart" ! -name "*.g.dart" ! -path '*/generated/*' | tr '\n' ' ' | xargs dart format --fix"
@@ -154,6 +158,10 @@ scripts:
 
   format-check:
     run: |
+      # The set -o pipefail option ensures that a pipeline returns the exit
+      # status of the first command that fails, instead of the last command.
+      set -o pipefail
+
       melos exec -c 1 --dir-exists="lib" -- "find . -name "*.dart" ! -name "*.g.dart" ! -path '*/generated/*' | tr '\n' ' ' | xargs dart format --output none --set-exit-if-changed" &&
       melos exec -c 1 --dir-exists="test" -- "find . -name "*.dart" ! -name "*.g.dart" ! -path '*/generated/*' | tr '\n' ' ' | xargs dart format --output none --set-exit-if-changed" &&
       melos exec -c 1 --dir-exists="integration_test" -- "find . -name "*.dart" ! -name "*.g.dart" ! -path '*/generated/*' | tr '\n' ' ' | xargs dart format --output none --set-exit-if-changed"
@@ -176,6 +184,10 @@ scripts:
 
   test-report:
     run: |
+      # The set -o pipefail option ensures that a pipeline returns the exit
+      # status of the first command that fails, instead of the last command.
+      set -o pipefail
+
       # cleanup from previous build and create new folders
       rm -fR $MELOS_ROOT_PATH/test_reports
       mkdir $MELOS_ROOT_PATH/test_reports
@@ -183,7 +195,7 @@ scripts:
       # run tests, generate junit reports in /test_reports/ & code coverage report
       melos exec -c 1 --dir-exists="test" -- \
        "flutter test --reporter expanded --coverage --machine | tojunit --output $MELOS_ROOT_PATH/test_reports/MELOS_PACKAGE_NAME.junit-report.xml"
-
+       
       # removes code coverage for generated code
       melos exec -c 1 --dir-exists="test" -- \
         lcov --remove coverage/lcov.info -o coverage/lcov.info --ignore-errors unused,unused \
