refactor: targets name

diff --git a/catalyst-gateway/tests/schemathesis_tests/Earthfile b/catalyst-gateway/tests/schemathesis_tests/Earthfile
--- a/catalyst-gateway/tests/schemathesis_tests/Earthfile
+++ b/catalyst-gateway/tests/schemathesis_tests/Earthfile
@@ -1,5 +1,6 @@
 VERSION 0.8
 
+# schemathesis image that targets only production ready endpoints
 package-schemathesis:
     FROM python:3.12-alpine3.20
     # TODO: https://github.com/input-output-hk/catalyst-voices/issues/465
@@ -32,37 +33,8 @@ package-schemathesis:
     ARG tag="latest"
     SAVE IMAGE schemathesis:$tag
 
-# test-schemathesis - Fuzzy test cat-gateway using openapi specs.
-test-schemathesis:
-    FROM earthly/dind:alpine-3.19-docker-25.0.5-r0
-    RUN apk update && apk add iptables-legacy curl # workaround for https://github.com/earthly/earthly/issues/3784
-    COPY schemathesis-docker-compose.yml .
-    LET api_spec="http://0.0.0.0:3030/docs/cat-gateway.json"
-    ARG seed
-
-    WITH DOCKER \
-        --compose schemathesis-docker-compose.yml \
-        --load schemathesis:latest=(+package-schemathesis --api_spec=$api_spec --seed=$seed) \
-        --load event-db:latest=(../../event-db+build) \
-        --load cat-gateway:latest=(../+package-cat-gateway-integration) \
-        --service event-db \
-        --service cat-gateway \
-        --allow-privileged
-
-        RUN docker run --net=host --name=st schemathesis:latest || echo fail > fail; \
-            docker cp st:/results/junit-report.xml junit-report.xml && \
-            docker cp st:/results/cassette.yaml cassette.yaml
-    END
-    WAIT
-        SAVE ARTIFACT junit-report.xml AS LOCAL schemathesis.junit-report.xml
-        SAVE ARTIFACT cassette.yaml AS LOCAL cassette.yaml
-    END
-    IF [ -f fail ]
-        RUN --no-cache echo "Schemathesis test failed. Check the logs for more details" && \
-            exit 1
-    END
-
-nightly-package-schemathesis:
+# schemathesis image that target all the endpoints (draft ones too)
+package-draft-schemathesis:
     FROM python:3.12-alpine3.20
     # TODO: https://github.com/input-output-hk/catalyst-voices/issues/465
     ARG api_spec
@@ -92,8 +64,38 @@ nightly-package-schemathesis:
     ARG tag="latest"
     SAVE IMAGE schemathesis:$tag
 
-# nightly-test-schemathesis - Fuzzy test cat-gateway using openapi specs.
-nightly-test-schemathesis:
+# test-ci-schemathesis - Fuzzy test cat-gateway using openapi specs.
+test-ci-schemathesis:
+    FROM earthly/dind:alpine-3.19-docker-25.0.5-r0
+    RUN apk update && apk add iptables-legacy curl # workaround for https://github.com/earthly/earthly/issues/3784
+    COPY schemathesis-docker-compose.yml .
+    LET api_spec="http://0.0.0.0:3030/docs/cat-gateway.json"
+    ARG seed
+
+    WITH DOCKER \
+        --compose schemathesis-docker-compose.yml \
+        --load schemathesis:latest=(+package-schemathesis --api_spec=$api_spec --seed=$seed) \
+        --load event-db:latest=(../../event-db+build) \
+        --load cat-gateway:latest=(../+package-cat-gateway-integration) \
+        --service event-db \
+        --service cat-gateway \
+        --allow-privileged
+
+        RUN docker run --net=host --name=st schemathesis:latest || echo fail > fail; \
+            docker cp st:/results/junit-report.xml junit-report.xml && \
+            docker cp st:/results/cassette.yaml cassette.yaml
+    END
+    WAIT
+        SAVE ARTIFACT junit-report.xml AS LOCAL schemathesis.junit-report.xml
+        SAVE ARTIFACT cassette.yaml AS LOCAL cassette.yaml
+    END
+    IF [ -f fail ]
+        RUN --no-cache echo "Schemathesis test failed. Check the logs for more details" && \
+            exit 1
+    END
+
+# nightly-test-draft-schemathesis - Fuzzy test cat-gateway using openapi specs.
+nightly-test-draft-schemathesis:
     FROM earthly/dind:alpine-3.19-docker-25.0.5-r0
     RUN apk update && apk add iptables-legacy curl zstd # workaround for https://github.com/earthly/earthly/issues/3784
     COPY schemathesis-docker-compose.yml .
@@ -102,7 +104,7 @@ nightly-test-schemathesis:
 
     WITH DOCKER \
         --compose schemathesis-docker-compose.yml \
-        --load schemathesis:latest=(+nightly-package-schemathesis --api_spec=$api_spec --seed=$seed) \
+        --load schemathesis:latest=(+package-draft-schemathesis --api_spec=$api_spec --seed=$seed) \
         --load event-db:latest=(../../event-db+build) \
         --load cat-gateway:latest=(../+package-cat-gateway-integration) \
         --service event-db \
@@ -124,7 +126,7 @@ nightly-test-schemathesis:
             exit 1
     END
 
-# nightly-test-schemathesis - Fuzzy test cat-gateway using openapi specs.
+# nightly-test-draft-schemathesis - Fuzzy test cat-gateway using openapi specs.
 nightly-test-dev-schemathesis:
     FROM earthly/dind:alpine-3.19-docker-25.0.5-r0
     RUN apk update && apk add iptables-legacy curl zstd # workaround for https://github.com/earthly/earthly/issues/3784
