fix(cat-gateway): Bump ci version and update rust earthfile to check for cache breaks

diff --git a/catalyst-gateway/Earthfile b/catalyst-gateway/Earthfile
--- a/catalyst-gateway/Earthfile
+++ b/catalyst-gateway/Earthfile
@@ -1,8 +1,18 @@
 VERSION 0.8
 
-IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.2.10 AS rust-ci
+IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.2.11 AS rust-ci
 
 #cspell: words rustfmt toolsets USERARCH stdcfgs
+
+# COPY_SRC:
+#   Copies the source code into the builder.
+COPY_SRC:
+    FUNCTION
+
+    COPY --keep-ts --dir \
+        Cargo.toml clippy.toml deny.toml rustfmt.toml \
+        bin \
+        .
 
 # sync-cfg: Synchronize local config with CI version.
 # Must be run by the developer manually.
@@ -13,7 +23,15 @@ sync-cfg:
 builder:
     DO rust-ci+SETUP
 
-    COPY --dir .cargo .config Cargo.* clippy.toml deny.toml rustfmt.toml bin .
+builder-src:
+    FROM +builder
+
+    # Cached copy of the source we build.
+    DO +COPY_SRC
+
+    # Generate Checksums of the source
+    DO rust-ci+FINGERPRINT_SRC
+    SAVE ARTIFACT ../src_fingerprint.txt 
 
 ## -----------------------------------------------------------------------------
 ##
@@ -24,7 +42,7 @@ builder:
 # check : Run check using the most efficient host tooling
 # CI Automated Entry point.
 check:
-    FROM +builder
+    FROM +builder-src
 
     DO rust-ci+EXECUTE --cmd="/scripts/std_checks.py"
 
@@ -36,7 +54,7 @@ all-hosts-check:
 # build : Build the catalyst-gateway service
 build:
     # Build the service
-    FROM +builder
+    FROM +builder-src
 
     DO rust-ci+EXECUTE \
         --cmd="/scripts/std_build.py" \
@@ -82,3 +100,21 @@ get-api-locally:
     FROM scratch
     COPY +build/doc/cat-gateway-api.json cat-gateway-api.json
     SAVE ARTIFACT cat-gateway-api.json AS LOCAL cat-gateway-api.json
+
+# build-src-check: Check for any caching issues with the source we are building against.
+check-builder-src-cache:
+    FROM +builder
+
+    COPY +builder-src/src_fingerprint.txt .
+
+    RUN --no-cache echo "Cache Disabled"
+
+    # Uncached copy of the source we build.
+    DO +COPY_SRC
+
+    # Generate Checksums of the source
+    DO rust-ci+FINGERPRINT_SRC --FINGERPRINT=src_fingerprint_uncached.txt
+
+    RUN diff src_fingerprint.txt ../src_fingerprint_uncached.txt \
+        || (echo "ERROR: Source fingerprints do not match. Caching Error Detected!!" && exit 1) \
+        && echo "Source fingerprints match. Caching OK."
