tag version without handling suffixes

diff --git a/catalyst_voices/Earthfile b/catalyst_voices/Earthfile
--- a/catalyst_voices/Earthfile
+++ b/catalyst_voices/Earthfile
@@ -126,13 +126,16 @@ build-web:
     ARG UPLOAD_DEBUG_SYMBOLS=false
     ARG tag='latest'
 
-    RUN echo "WORKDIR -> $WORKDIR, UPLOAD_DEBUG_SYMBOLS -> $UPLOAD_DEBUG_SYMBOLS, tag -> $tag"
+    DO +PREPARE_BUILD_ARGS --tag=$tag
+
+    RUN echo "build_name -> $(cat build_name)"
+    RUN echo "build_number -> $(cat build_number)"
 
     DO flutter-ci+BUILD_WEB \
         --WORKDIR=$WORKDIR \
         --BUILD_MODE='--release' \
-        --BUILD_NAME='0.1.0' \
-        --BUILD_NUMBER=$(date +%s) \
+        --BUILD_NAME=$(cat build_name) \
+        --BUILD_NUMBER=$(cat build_number) \
         --TARGET=lib/configs/main_web.dart \
         --UPLOAD_DEBUG_SYMBOLS=$UPLOAD_DEBUG_SYMBOLS \
         --SENTRY_ORG='iohk-j4' \
@@ -161,3 +164,30 @@ docker:
    ARG tag="latest"
 
    SAVE IMAGE ${container}:${tag}
+
+PREPARE_BUILD_ARGS:
+    FUNCTION
+    ARG tag='latest'
+    ARG allow_build_name_suffix=true
+
+    RUN bash -c '\
+        set -e; \
+
+        _build_name=""
+        _build_number=""
+
+        if echo "$tag" | grep -q "/" && ! echo "$tag" | grep -q "^voices/"; then
+            echo "Invalid prefix found in tag '\''$tag'\''. Using default values."
+        else
+            _build_name=$(echo "$tag" | sed -n "s|.*v\([0-9]\+\.[0-9]\+\.[0-9]\+\).*|\1|p"); \
+
+            if echo "$tag" | grep -q "+"; then \
+                _build_number=$(echo "$tag" | cut -d"+" -f2 | cut -d"-" -f1); \
+            fi; \
+        fi
+
+        FINAL_BUILD_NAME=${_build_name:-"0.1.0"}; \
+        FINAL_BUILD_NUMBER=${_build_number:-$(date +%s)}; \
+        echo -n "$FINAL_BUILD_NAME" > build_name; \
+        echo -n "$FINAL_BUILD_NUMBER" > build_number; \
+    '
