feat: adds logging

diff --git a/catalyst_voices/test_driver/Earthfile b/catalyst_voices/test_driver/Earthfile
--- a/catalyst_voices/test_driver/Earthfile
+++ b/catalyst_voices/test_driver/Earthfile
@@ -1,8 +1,9 @@
-VERSION --try --global-cache --arg-scope-and-set --use-function-keyword 0.7
+VERSION --try --global-cache --arg-scope-and-set 0.7
 
 integration-test-web:
     FROM ../+build
     ARG browser
+    LET driver_port = 4444
 
     IF [ $browser = "chrome" ]
         LET driver = "chromedriver"
@@ -15,11 +16,21 @@ integration-test-web:
     IF [ $browser = "edge" ]
         LET driver = "msedgedriver"
     END
-
-    RUN ($driver --port=4444 &) && \
+    RUN ($driver --port=$driver_port > $driver.log &) && \
             flutter drive --driver=test_driver/integration_test.dart \
                 --target=integration_test/main.dart \
-                    --flavor development -d web-server --profile --browser-name=$browser
+                    --flavor development -d web-server --profile \
+                        --browser-name=$browser --driver-port=$driver_port || echo fail > fail
+    # Using WAIT instead of TRY because TRY/CATCH/FINALLY does not (currently) support expanding args for SAVE ARTIFACT paths
+    WAIT
+        SAVE ARTIFACT $driver.log AS LOCAL $driver.log
+    END
+    IF [ -f fail ]
+        RUN echo ""$browser" integration test failed" && \
+            echo "Printing "$driver" logs..." && \
+            cat $driver.log && \
+            exit 1
+    END
 
 test-web-all:
     BUILD +integration-test-web \
