pre build images job, try 6

diff --git a/.github/workflows/nightly-ci.yml b/.github/workflows/nightly-ci.yml
--- a/.github/workflows/nightly-ci.yml
+++ b/.github/workflows/nightly-ci.yml
@@ -21,6 +21,11 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
+      - name: Setup SSH Agent
+        uses: webfactory/ssh-agent@v0.9.1
+        with:
+          ssh-private-key: ${{ secrets.QA_REPO_SSH_KEY }}
+
       - name: Install Forge
         uses: input-output-hk/catalyst-forge/actions/install@ci/v1.10.0
         with:
@@ -38,19 +43,43 @@ jobs:
           args: ./catalyst-gateway/tests/+all-images
 
       - name: Save image to tar
-        run: docker save event-db:latest -o event-db.tar
+        run: |
+          docker save cat-gateway:latest -o cat-gateway.tar
+          docker save event-db:latest -o event-db.tar
+          docker save api-tests-runner:latest -o api-tests-runner.tar
+          docker save schemathesis-runner:latest -o schemathesis-runner.tar
+          docker save rust-tests-runner:latest -o rust-tests-runner.tar
+          docker save event-db:v1 -o event-db-v1.tar
+          docker save haproxy-node:latest -o haproxy-node.tar
+          docker save cat-devnet:latest -o cat-devnet.tar
+          mkdir all-images
+          mv *.tar all-images/
 
       - uses: actions/upload-artifact@v4
         with:
-          name: event-db
-          path: event-db.tar
+          name: all-images
+          path: all-images/
 
   tests:
     name: Cat-Gateway integration tests
     runs-on: ubuntu-latest
-    needs: build-images
     steps:
       - uses: actions/checkout@v4
+
+      - name: Free Disk Space (Ubuntu)
+        uses: jlumbroso/free-disk-space@main
+        with:
+          # this might remove tools that are actually needed,
+          # if set to "true" but frees about 6 GB
+          tool-cache: false
+          # all of these default to true, but feel free to set to
+          # "false" if necessary for your workflow
+          android: true
+          dotnet: false
+          haskell: false
+          large-packages: false
+          docker-images: false
+          swap-storage: true
 
       - name: Install Forge
         uses: input-output-hk/catalyst-forge/actions/install@ci/v1.10.0
@@ -65,21 +94,93 @@ jobs:
         id: get-images
         uses: actions/download-artifact@v4
         with:
-          name: event-db
-          path: .
+          name: all-images
+          path: all-images/
 
       - name: Load image
-        run: docker load -i event-db.tar
-
-      - name: Start event-db
-        if: always()
+        id: load-images
         run: |
-          docker compose -f catalyst-gateway/tests/docker-compose.yml up event-db
+          docker load -i cat-gateway.tar
+          docker load -i event-db.tar
+          docker load -i api-tests-runner.tar
+          docker load -i schemathesis-runner.tar
+          docker load -i rust-tests-runner.tar
+          docker load -i event-db-v1.tar
+          docker load -i haproxy-node.tar
+
+      - name: Rust integration tests
+        if: ${{ steps.load-images.conclusion == 'success' }}
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose.yml up rust-tests-runner --exit-code-from rust-tests-runner
+          docker compose -f catalyst-gateway/tests/docker-compose.yml down
+
+      - name: Spin up catalyst-gateway
+        id: gateway-started
+        if: ${{ steps.load-images.conclusion == 'success' }}
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose.yml up cat-gateway --detach
+
+      - name: Wait for cat-gateway to become healthy
+        id: gateway-healthy
+        if: ${{ steps.gateway-started.conclusion == 'success' }}
+        run: |
+          echo "Waiting for container to be healthy..."
+          for i in {1..500}; do
+            STATUS=$(docker inspect --format='{{.State.Health.Status}}' cat-gateway)
+            echo "Health status: $STATUS"
+            if [ "$STATUS" == "healthy" ]; then
+              echo "Container is healthy!"
+              break
+            fi
+            if [ "$STATUS" == "unhealthy" ]; then
+              echo "Container became unhealthy."
+              break
+            fi
+            sleep 5
+          done
+          
+          if [ "$STATUS" != "healthy" ]; then
+            docker compose -f catalyst-gateway/tests/docker-compose.yml logs cat-gateway
+            exit 1
+          fi
+
+      - name: Integration API tests
+        if: ${{ steps.gateway-healthy.conclusion == 'success' }}
+        env:
+          API_TEST_MARKS: "preprod_indexing or unmarked"
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose.yml up api-tests-runner --exit-code-from api-tests-runner
+          docker cp api-tests-runner:/poetry/junit-report.xml ./api-tests${{ env.REPORT_EXT }}
+          docker cp api-tests-runner:/poetry/coverage.lcov ./api-tests${{ env.COVERAGE_EXT }}
+
+      - name: Integration health tests
+        if: ${{ steps.gateway-healthy.conclusion == 'success' }}
+        env:
+          API_TEST_MARKS: "health_endpoint"
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose.yml up api-tests-runner --exit-code-from api-tests-runner
+  #
+  #      - name: Collect and upload test reports
+  #        uses: actions/upload-artifact@v4
+  #        if: success() || failure()
+  #        with:
+  #          name: test-reports-gateway
+  #          path: "**/*${{ env.REPORT_EXT }}"
+  #          if-no-files-found: error
+  #          retention-days: 1
+  #
+  #      - name: Collect and upload test coverage
+  #        uses: actions/upload-artifact@v4
+  #        if: success() || failure()
+  #        with:
+  #          name: coverage-reports-gateway
+  #          path: "**/*${{ env.COVERAGE_EXT }}"
+  #          if-no-files-found: error
+  #          retention-days: 1
 
   devnet-tests:
     name: Cat-Gateway devnet integration tests
     runs-on: ubuntu-latest
-    needs: build-images
     steps:
       - uses: actions/checkout@v4
 
@@ -96,16 +197,73 @@ jobs:
         id: get-images
         uses: actions/download-artifact@v4
         with:
-          name: event-db
-          path: .
+          name: all-images
+          path: all-images/
 
       - name: Load image
-        run: docker load -i event-db.tar
-
-      - name: Start event-db
-        if: always()
+        id: load-images
         run: |
-          docker compose -f catalyst-gateway/tests/docker-compose.yml up event-db
+          docker load -i cat-gateway.tar
+          docker load -i event-db.tar
+          docker load -i api-tests-runner.tar
+          docker load -i schemathesis-runner.tar
+          docker load -i rust-tests-runner.tar
+          docker load -i event-db-v1.tar
+          docker load -i haproxy-node.tar
+          docker load -i cat-devnet.tar
+
+      - name: Spin up devnet
+        if: ${{ steps.load-images.conclusion == 'success' }}
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose-devnet.yml up cat-devnet -d
+
+      - name: Wait for cat-devnet to become healthy
+        run: |
+          echo "Waiting for container to be healthy..."
+          for i in {1..500}; do
+            STATUS=$(docker inspect --format='{{.State.Health.Status}}' cat-devnet)
+            echo "Health status: $STATUS"
+            if [ "$STATUS" == "healthy" ]; then
+              echo "Container is healthy!"
+              break
+            fi
+            if [ "$STATUS" == "unhealthy" ]; then
+              echo "Container became unhealthy."
+              docker compose -f catalyst-gateway/tests/docker-compose-devnet.yml logs cat-devnet
+              exit 1
+            fi
+            sleep 5
+          done
+
+      - name: Spin up catalyst-gateway
+        id: gateway-started
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose-devnet.yml up cat-gateway -d
+
+      - name: Wait for cat-gateway to become healthy
+        id: gateway-healthy
+        if: ${{ steps.gateway-started.conclusion == 'success' }}
+        run: |
+          echo "Waiting for container to be healthy..."
+          for i in {1..500}; do
+            STATUS=$(docker inspect --format='{{.State.Health.Status}}' cat-gateway)
+            echo "Health status: $STATUS"
+            if [ "$STATUS" == "healthy" ]; then
+              echo "Container is healthy!"
+              break
+            fi
+            if [ "$STATUS" == "unhealthy" ]; then
+              echo "Container became unhealthy."
+              docker compose -f catalyst-gateway/tests/docker-compose-devnet.yml logs cat-gateway
+              exit 1
+            fi
+            sleep 5
+          done
+
+      - name: Schemathesis tests
+        if: ${{ steps.gateway-healthy.conclusion == 'success' }}
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose-devnet.yml up schemathesis-runner --exit-code-from schemathesis-runner
 
 #  ci-nightly:
 #    uses: input-output-hk/catalyst-forge/.github/workflows/ci.yml@ci/v1.10.0
