pre build images job, try 3

diff --git a/.github/workflows/nightly-ci.yml b/.github/workflows/nightly-ci.yml
--- a/.github/workflows/nightly-ci.yml
+++ b/.github/workflows/nightly-ci.yml
@@ -15,33 +15,11 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  ci-nightly:
-    uses: input-output-hk/catalyst-forge/.github/workflows/ci.yml@ci/v1.10.0
-    with:
-      forge_version: 0.21.0
-      skip_deploy: true
-      skip_release: true
-
-  tests:
-    name: nightly tests
+  build-images:
+    name: Build images
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-
-      - name: Free Disk Space (Ubuntu)
-        uses: jlumbroso/free-disk-space@main
-        with:
-          # this might remove tools that are actually needed,
-          # if set to "true" but frees about 6 GB
-          tool-cache: false
-          # all of these default to true, but feel free to set to
-          # "false" if necessary for your workflow
-          android: true
-          dotnet: false
-          haskell: false
-          large-packages: false
-          docker-images: false
-          swap-storage: true
 
       - name: Install Forge
         uses: input-output-hk/catalyst-forge/actions/install@ci/v1.10.0
@@ -53,89 +31,201 @@ jobs:
         uses: input-output-hk/catalyst-forge/actions/setup@ci/v1.10.0
 
       - name: Prepare artifacts
-        id : images
+        id: images
         uses: input-output-hk/catalyst-forge/actions/run@ci/v1.10.0
         with:
           command: run
           args: ./catalyst-gateway/tests/+all-images
 
-      - name: Spin up catalyst-gateway
-        id: gateway-started
-        if: ${{ steps.images.conclusion == 'success' }}
-        run: |
-          docker compose -f catalyst-gateway/tests/docker-compose.yml up cat-gateway --detach
+      - name: Save image to tar
+        run: docker save event-db:latest -o event-db.tar
 
-      - name: Wait for cat-gateway to become healthy
-        id: gateway-healthy
-        if: ${{ steps.gateway-started.conclusion == 'success' }}
-        run: |
-          echo "Waiting for container to be healthy..."
-          for i in {1..500}; do
-            STATUS=$(docker inspect --format='{{.State.Health.Status}}' cat-gateway)
-            echo "Health status: $STATUS"
-            if [ "$STATUS" == "healthy" ]; then
-              echo "Container is healthy!"
-              break
-            fi
-            if [ "$STATUS" == "unhealthy" ]; then
-              echo "Container became unhealthy."
-              docker logs cat-gateway
-              exit 1
-            fi
-            sleep 5
-          done
+      - uses: actions/upload-artifact@v4
+        with:
+          name: event-db
+          path: event-db.tar
 
-      - name: Schemathesis tests
-        id: schemathesis-tests
-        if: ${{ steps.gateway-healthy.conclusion == 'success' }}
-        run: |
-          export HYPOTHESIS_MAX_EXAMPLES=5000
-          export MAX_RESPONSE_TIME=25000
-          docker compose -f catalyst-gateway/tests/docker-compose.yml up schemathesis-runner --exit-code-from schemathesis-runner
+  tests:
+    name: Cat-Gateway integration tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
 
-      - name: Spin up catalyst-gateway with haproxy
-        id: gateway-with-proxy-started
-        env:
-          EVENT_DB_URL: "haproxy:18080"
-          INDEX_DB_URL: "haproxy:18090"
-        run: |
-          docker stop cat-gateway || true
-          docker compose -f catalyst-gateway/tests/docker-compose.yml up haproxy --detach
-          docker compose -f catalyst-gateway/tests/docker-compose.yml up cat-gateway --detach
+      - name: Install Forge
+        uses: input-output-hk/catalyst-forge/actions/install@ci/v1.10.0
+        with:
+          enable_caching: "true"
+          version: 0.21.0
 
-      - name: Wait for cat-gateway to become healthy
-        id: gateway-with-proxy-healthy
-        if: ${{ steps.gateway-with-proxy-started.conclusion == 'success' }}
-        run: |
-          echo "Waiting for container to be healthy..."
-          for i in {1..500}; do
-            STATUS=$(docker inspect --format='{{.State.Health.Status}}' cat-gateway)
-            echo "Health status: $STATUS"
-            if [ "$STATUS" == "healthy" ]; then
-              echo "Container is healthy!"
-              break
-            fi
-            if [ "$STATUS" == "unhealthy" ]; then
-              echo "Container became unhealthy."
-              docker logs cat-gateway
-              exit 1
-            fi
-            sleep 5
-          done
+      - name: Setup
+        uses: input-output-hk/catalyst-forge/actions/setup@ci/v1.10.0
 
-      - name: Integration health thru proxy tests
-        if: ${{ steps.gateway-with-proxy-healthy.conclusion == 'success' }}
-        env:
-          API_TEST_MARKS: "health_with_proxy_endpoint"
-        run: |
-          docker compose -f catalyst-gateway/tests/docker-compose.yml up api-tests-runner --exit-code-from api-tests-runner
+      - name: Get artifacts
+        id: get-images
+        uses: actions/download-artifact@v4
+        with:
+          name: event-db.tar
+          path: .
 
-  slack-notification:
-    needs: tests
-    if: ${{ always() && needs.tests.result == 'failure' }}
-    uses: input-output-hk/catalyst-ci/.github/workflows/qa-notify.yml@master
-    with:
-      failed_repo: ${{ github.repository }}
-      failed_run_id: ${{ github.run_id }}
-    secrets:
-      slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
+      - name: Load image
+        run: docker load -i event-db.tar
+
+      - name: Start event-db
+        if: always()
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose.yml up event-db
+
+  devnet-tests:
+    name: Cat-Gateway devnet integration tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Forge
+        uses: input-output-hk/catalyst-forge/actions/install@ci/v1.10.0
+        with:
+          enable_caching: "true"
+          version: 0.21.0
+
+      - name: Setup
+        uses: input-output-hk/catalyst-forge/actions/setup@ci/v1.10.0
+
+      - name: Get artifacts
+        id: get-images
+        uses: actions/download-artifact@v4
+        with:
+          name: event-db.tar
+          path: .
+
+      - name: Load image
+        run: docker load -i event-db.tar
+
+      - name: Start event-db
+        if: always()
+        run: |
+          docker compose -f catalyst-gateway/tests/docker-compose.yml up event-db
+
+#  ci-nightly:
+#    uses: input-output-hk/catalyst-forge/.github/workflows/ci.yml@ci/v1.10.0
+#    with:
+#      forge_version: 0.21.0
+#      skip_deploy: true
+#      skip_release: true
+#
+#  tests:
+#    name: nightly tests
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Free Disk Space (Ubuntu)
+#        uses: jlumbroso/free-disk-space@main
+#        with:
+#          # this might remove tools that are actually needed,
+#          # if set to "true" but frees about 6 GB
+#          tool-cache: false
+#          # all of these default to true, but feel free to set to
+#          # "false" if necessary for your workflow
+#          android: true
+#          dotnet: false
+#          haskell: false
+#          large-packages: false
+#          docker-images: false
+#          swap-storage: true
+#
+#      - name: Install Forge
+#        uses: input-output-hk/catalyst-forge/actions/install@ci/v1.10.0
+#        with:
+#          enable_caching: "true"
+#          version: 0.21.0
+#
+#      - name: Setup
+#        uses: input-output-hk/catalyst-forge/actions/setup@ci/v1.10.0
+#
+#      - name: Prepare artifacts
+#        id : images
+#        uses: input-output-hk/catalyst-forge/actions/run@ci/v1.10.0
+#        with:
+#          command: run
+#          args: ./catalyst-gateway/tests/+all-images
+#
+#      - name: Spin up catalyst-gateway
+#        id: gateway-started
+#        if: ${{ steps.images.conclusion == 'success' }}
+#        run: |
+#          docker compose -f catalyst-gateway/tests/docker-compose.yml up cat-gateway --detach
+#
+#      - name: Wait for cat-gateway to become healthy
+#        id: gateway-healthy
+#        if: ${{ steps.gateway-started.conclusion == 'success' }}
+#        run: |
+#          echo "Waiting for container to be healthy..."
+#          for i in {1..500}; do
+#            STATUS=$(docker inspect --format='{{.State.Health.Status}}' cat-gateway)
+#            echo "Health status: $STATUS"
+#            if [ "$STATUS" == "healthy" ]; then
+#              echo "Container is healthy!"
+#              break
+#            fi
+#            if [ "$STATUS" == "unhealthy" ]; then
+#              echo "Container became unhealthy."
+#              docker logs cat-gateway
+#              exit 1
+#            fi
+#            sleep 5
+#          done
+#
+#      - name: Schemathesis tests
+#        id: schemathesis-tests
+#        if: ${{ steps.gateway-healthy.conclusion == 'success' }}
+#        run: |
+#          export HYPOTHESIS_MAX_EXAMPLES=5000
+#          export MAX_RESPONSE_TIME=25000
+#          docker compose -f catalyst-gateway/tests/docker-compose.yml up schemathesis-runner --exit-code-from schemathesis-runner
+#
+#      - name: Spin up catalyst-gateway with haproxy
+#        id: gateway-with-proxy-started
+#        env:
+#          EVENT_DB_URL: "haproxy:18080"
+#          INDEX_DB_URL: "haproxy:18090"
+#        run: |
+#          docker stop cat-gateway || true
+#          docker compose -f catalyst-gateway/tests/docker-compose.yml up haproxy --detach
+#          docker compose -f catalyst-gateway/tests/docker-compose.yml up cat-gateway --detach
+#
+#      - name: Wait for cat-gateway to become healthy
+#        id: gateway-with-proxy-healthy
+#        if: ${{ steps.gateway-with-proxy-started.conclusion == 'success' }}
+#        run: |
+#          echo "Waiting for container to be healthy..."
+#          for i in {1..500}; do
+#            STATUS=$(docker inspect --format='{{.State.Health.Status}}' cat-gateway)
+#            echo "Health status: $STATUS"
+#            if [ "$STATUS" == "healthy" ]; then
+#              echo "Container is healthy!"
+#              break
+#            fi
+#            if [ "$STATUS" == "unhealthy" ]; then
+#              echo "Container became unhealthy."
+#              docker logs cat-gateway
+#              exit 1
+#            fi
+#            sleep 5
+#          done
+#
+#      - name: Integration health thru proxy tests
+#        if: ${{ steps.gateway-with-proxy-healthy.conclusion == 'success' }}
+#        env:
+#          API_TEST_MARKS: "health_with_proxy_endpoint"
+#        run: |
+#          docker compose -f catalyst-gateway/tests/docker-compose.yml up api-tests-runner --exit-code-from api-tests-runner
+#
+#  slack-notification:
+#    needs: tests
+#    if: ${{ always() && needs.tests.result == 'failure' }}
+#    uses: input-output-hk/catalyst-ci/.github/workflows/qa-notify.yml@master
+#    with:
+#      failed_repo: ${{ github.repository }}
+#      failed_run_id: ${{ github.run_id }}
+#    secrets:
+#      slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
